foreground              #060606
background              #F1D9C2
selection_foreground    #F1D9C2
selection_background    #060606
cursor                  #2A2A3A
cursor_text_color       #FFFFFF

active_tab_foreground     #F1D9C2
active_tab_background     #525062
inactive_tab_foreground   #525062
inactive_tab_background   #F1D9C2

# black
color0      #523D29
color8      #8F7257

# red
color1      #CCCCFF
color9      #AAAAF0

# green
color2      #FFDACC
color10     #F0BDAA

# yellow
color3      #D2CCFF
color11     #B2AAF0

# blue
color4      #E6BF9A
color12     #E6BF9A

# magenta
color5      #E6AE9A
color13     #E6AE9A

# cyan
color6      #A29AE6
color14     #A29AE6

# white
color7      #CCCCFF
color15     #AAAAF0
